In [5]:
# import pandas
import pandas as pd

In [7]:
data = [10,20,30,40]
series = pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [11]:
# create series using dictionary
data = {'a': 10, 'b' : 20, 'c': 30}
series = pd.Series(data)
print(series)

a    10
b    20
c    30
dtype: int64


In [13]:
series.replace(20,40)

a    10
b    40
c    30
dtype: int64

In [15]:
# create series using numpy array
import numpy as np

data = np.array([100, 200, 300])
series = pd.Series(data, index=['a','b','c'])
print(series)

a    100
b    200
c    300
dtype: int32


In [19]:
# create pandas dataframe from dictionary of list
import pandas as pd

data = {'Name': ['Alice', 'bob', 'Marry'], 'Age': [25, 30,34], 'Country' : ['USA', 'UK', 'JAPAN']}
df = pd.DataFrame(data)
print(df)

    Name  Age Country
0  Alice   25     USA
1    bob   30      UK
2  Marry   34   JAPAN


In [21]:
# create pandas dataframe from numpy array
import numpy as np

array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)
df = pd.DataFrame(array,columns=['A','B','C'])
print(df)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9
